---
title: Regresyon
subtitle: İKT 533
author: Murat Taşdemir
# Short author for footline
short-author: MT
institute: İMÜ
short-inst: "İMÜ"
date: "`r format(Sys.time(), '%d %B %Y')`"
fontsize: 12pt
output: 
  beamer_presentation: 
    colortheme: default
    fig_caption: yes
    fonttheme: default
    incremental: no
    keep_tex: yes
    theme: metropolis
    toc: no
    latex_engine: xelatex
    template: sunu.beamer
    #includes:
    #  in_header: header.tex
    #  before_body: doc_prefix.tex
    #  after_body: doc_suffix.tex
# Set aspect ratio 43 or 169
classoption: ["fleqn","aspectratio=43"]
header-includes:
  - \usepackage{polyglossia}
  - \setdefaultlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption}
  - \usepackage{amsmath}
  - \usepackage{setspace}
  - \usepackage{float}
  - \usepackage{multirow}
  - \usefonttheme{professionalfonts}
  - \usepackage{mathtools}
  - \usepackage{unicode-math}
  - \setmathfont{TeX Gyre Pagella Math}
  - \newcommand*\rot{\rotatebox{90}} 
  # Suppress section slides
  - \AtBeginSection{}
  # Below two commands are to spread out list items in slides vertically
  - \let\olditem\item
  - \renewcommand{\item}{\olditem\vspace{\fill}}  
  - \useinnertheme{circles}
  - \definecolor{mLightBrown}{HTML}{EB811B}
  - \setbeamercolor{itemize item}{fg=mLightBrown}
  - \setbeamertemplate{enumerate items}{\bf\insertenumlabel.}
  - \setbeamercolor{item projected}{bg=mLightBrown,fg=black}
  #- \setbeamercolor{enumerate item}{fg=orange}
    # Remove footline
  - \metroset{progressbar=none, numbering=fraction}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## HANGİ OKULA GİTMELİ?

* Özel
* Devlet

## Tesadüfileştirme Yerine Regresyon

- Her zaman tasadüfileştirilmiş deney yapma şansımız yok.
- Regresyon kullanarak nedensel etkiyi tahmin edebiliriz (dikkat!)
- İki alternatif için de potansiyel sonuçları tanımlayalım.
- Özel okullar (üniversite) verilen paraya değer mi? (ABD bağlamında)

  - $Y_{1i}$: özel üniversiteye giden ($P_i=1$) $i$ bireyinin ücreti
  - $Y_{0i}$: $i$ bireyinin karşıolgusal ($P_i=0$) sonucu

## Yapısal (gerçek nedensel) ilişki

- Özel $Y_{0i}$ lerin (ortalamada) daha yüksek olduğunu varsayalım. 

  - \alert{Dikkat edin} bu $Y_i$'nin $P_i$'ye bağlı olarak değiştiği anlamına gelir.
  - Regresyon kullanarak seçilim yanlılığınız azaltabilir, hatta yok edebiliriz
   
- $Y_{0i}=\alpha_i+\eta_i$ ve $Y_{1i}-Y_{0i}=\beta$ olsun

  - $\alpha_i$: devlet okuluna giden bireyin ortalama ücreti
  - $\eta_i$: tesadüfi kısım
  - $\beta$: özel üniversiteye gitmenin ücretteki etkisi (müdahale etkisi)

## Regresyon ve Koşullu Ortalama Varsayımı (CIA)

- Tesadüfi kısımın beklenen değerinin sıfır olduğunu biliyoruz: $E[\eta_i]=0$.
- Bu gerçek, $E[\eta_i|P_i]$ koşullu beklenen değerinin sıfır olmadığı anlamına \alert{gelmez.}. 
- Aksine okul seçimini etkileyen başka değişkenler olduğu için  $E[\eta_i|P_i]\neq 0$ olduğunu biliyoruz (böyle bir yapısal ilişki varsaydık yukarıda)
- Gözlemleyebildiğimiz $X_i$ (vektör) değişkenlerinin aşağıdaki *koşullu bağımsızlık varsayımı*nı (CIA) sağladığını varsayacağız:
\[E[\eta_i|P_i,X_i]=E[\eta_i|X_i]=\gamma'X_i\]

## Koşullu Bağımsızlık

- \alert{Dikkat!} $X_i$ değişkenlerinin \alert{gözlemlenebildiği} varsayılıyor.
- $X_i$ değişkenlerini regresyonda kontrol edersek, 
\[Y_i=\alpha+\gamma'X_i+\beta P_i+u_i\]

## Regresyon 

- Buradan 
\[Y_i=\alpha+\gamma'X_i+\beta P_i+u_i\]

 - $\beta$: nedensel etki
 - $\gamma$: ilgilenmiyoruz
 
